### ISSUE TITLE
Galleria: thumbnails are shifted even if number of items <= numVisible

### ISSUE THREAD

**Issue by kimscholte** [primefaces/primefaces#10292]
### Describe the bug

The shifting seems to only occur in some conditions, eg when using the p:galleria with 5 photo's and the numVisible attribute set to "6"

I would suggest to not shift when number of items <= numVisible

Relevant file:
https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/resources/META-INF/resources/primefaces/galleria/0-galleriathumbnail.js

It seems that the block in `updated`:
```
else if (this.thumbnailItems.length - this.state.numVisible + this.getMedianIndex() < this.options.activeIndex) {
  totalShiftedItems = this.state.numVisible - this.thumbnailItems.length;
}
```
is executed, and sets the `totalShiftedItems` to 1.

### Reproducer

[primefaces-test-galleria.tar.gz](https://github.com/primefaces/primefaces/files/11947970/primefaces-test-galleria.tar.gz)

### Expected behavior

The banner containing the thumbnails should stay static when the number of images is smaller than the number of thumbs one wants to show

### PrimeFaces edition

Community + Elite

### PrimeFaces version

12.0.0 + 12.0.4

### JSF implementation

All

### JSF version

2.2 + 2.3

### Java version

1.8

**Comment by melloware** [comment]
@kimscholte can you review my PR or test this MonkeyPatch?

```js
if (PrimeFaces.widget.Galleria) {
    $.prime.galleriaThumbnail.prototype.updated = function(prevOptions, prevState) {
        var totalShiftedItems = this.state.totalShiftedItems;

        if (prevState.numVisible !== this.state.numVisible || prevOptions.activeIndex !== this.options.activeIndex) {
            if (this.options.activeIndex <= this.getMedianIndex() || this.thumbnailItems.length <= this.state.numVisible) {
                totalShiftedItems = 0;
            } else if (this.thumbnailItems.length - this.state.numVisible + this.getMedianIndex() < this.options.activeIndex) {
                totalShiftedItems = this.state.numVisible - this.thumbnailItems.length;
            } else if (this.thumbnailItems.length - this.state.numVisible < this.options.activeIndex && this.state.numVisible % 2 === 0) {
                totalShiftedItems = (this.options.activeIndex * -1) + this.getMedianIndex() + 1;
            } else {
                totalShiftedItems = (this.options.activeIndex * -1) + this.getMedianIndex();
            }

            if (totalShiftedItems !== this.state.totalShiftedItems) {
                this.setState({
                    totalShiftedItems: totalShiftedItems
                });
            }

            var transform = this.options.isVertical ? 'translate3d(0, ' + (totalShiftedItems * (100 / this.state.numVisible)) + '%, 0)' : 'translate3d(' + (totalShiftedItems * (100 / this.state.numVisible)) + '%, 0, 0)';
            this.container.css('transform', transform);

            if (prevOptions.activeIndex !== this.options.activeIndex) {
                this.container.removeClass('ui-items-hidden').css('transition', 'transform 500ms ease 0s');
            }

            this._updateUI();
        }
    };
};
```

**Comment by melloware** [comment]
Fixed version with MonkeyPatch applied:
[pf-10292.zip](https://github.com/primefaces/primefaces/files/11950776/pf-10292.zip)

Seems like its working fine now.

**Comment by fcorneli** [comment]
Unfortunately it still doesn't work with the proposed monkey patch on our application. When I click the fourth thumbnail, the fifth thumbnail still disappears within the thumbnail bar.

**Comment by fcorneli** [comment]
When I directly click the fifth thumbnail, I get to see the corresponding image, but the thumbnail bar scrolls away the fifth thumbnail.

**Comment by melloware** [comment]
Ok so it looks better in the reproducer but it is still not correct. Have you looked into it?

**Comment by fcorneli** [comment]
@melloware OK, my bad. I messed something up while testing the monkey patch. Against your 13.0.0-SNAPSHOT branch it works.
