### ISSUE TITLE
DataExporter: Delivers "No enum constant com.sun.faces.context.ExternalContextImpl.PREDEFINED_COOKIE_PROPERTIES.SameSite"

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#11908]
### Describe the bug

I was trying to migrate my app from PF13/JakarteEE8/Java8/Payara 5 to PF 14/JakartaEE10/Java21/Payara 6. 

The DataExporter is not working anymore. I get this error:

```
[2024-05-10T17:20:10.323+0200] [Payara 6.2024.3] [SEVERE] [] [org.primefaces.application.exceptionhandler.PrimeExceptionHandler] [tid: _ThreadID=135 _ThreadName=http-thread-pool::http-listener-1(2)] [timeMillis: 1715354410323] [levelValue: 1000] [[
  No enum constant com.sun.faces.context.ExternalContextImpl.PREDEFINED_COOKIE_PROPERTIES.SameSite
java.lang.IllegalArgumentException: No enum constant com.sun.faces.context.ExternalContextImpl.PREDEFINED_COOKIE_PROPERTIES.SameSite
	at java.base/java.lang.Enum.valueOf(Enum.java:293)
	at com.sun.faces.context.ExternalContextImpl$PREDEFINED_COOKIE_PROPERTIES.valueOf(ExternalContextImpl.java:102)
	at com.sun.faces.context.ExternalContextImpl.addResponseCookie(ExternalContextImpl.java:765)
	at jakarta.faces.context.ExternalContextWrapper.addResponseCookie(ExternalContextWrapper.java:646)
	at jakarta.faces.context.ExternalContextWrapper.addResponseCookie(ExternalContextWrapper.java:646)
```

My hope would be that this is somehow a "known" issue, which somebody could quickly answer, or at least give a hint whether this is a PF or Payara issue. Otherwise, I will of course need to dig deeper into this issue and prepare a reproducer. 

Many thanks in advance for your response.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.0

### JSF implementation

Mojarra

### JSF version

4

### Java version

21

**Comment by melloware** [comment]
From the stack trace looks like a Mojarra / Payara issue.  As the error is com.sun.faces.

**Comment by melloware** [comment]
@tuerker found it: https://forum.primefaces.org/viewtopic.php?t=80045

Its a mojarra bug which should be already fixed in newer versions: https://github.com/eclipse-ee4j/mojarra/issues/5165

**Comment by tuerker** [comment]
@melloware many thanks for the hint. it is a pity that this issue is still persistent in the latest payara version.

**Comment by tandraschko** [comment]
Nothing new:
https://github.com/payara/Payara/issues/6578#issuecomment-2099820777

**Comment by tuerker** [comment]
@melloware Which EE server you would suggest?

**Comment by melloware** [comment]
@tuerker this is a hot topic and everyone has their opinion but I personally have never had an issue with FREE Wildfly.   When Mojarra updates its really easy to just upgrade Mojarra JAR yourself to the latest so you wouldn't be stuck with Payara issues like that.

I know others really like TomEE or OpenLiberty as well.

**Comment by seinecle** [comment]
Using payara-micro version 6.2024.10 and the issue is fixed.
