### ISSUE TITLE
Double Loading of JS Scripts

### ISSUE THREAD

**Issue by kamilkrzywanski** [primefaces/primefaces#13661]
### **I am reopening the issue, but this time, reading with understanding will be appreciated.**

Hello,

I am currently migrating my project from PrimeFaces 6.1 to the latest version, and I've encountered an issue that appeared with PrimeFaces 6.2. Specifically, I am seeing the following error:

"Uncaught SyntaxError: Failed to execute 'appendChild' on 'Node': Identifier 'xxx' has already been declared."

It seems like the scripts are being loaded twice when using my "popup" mechanism.

You can find a working example with PrimeFaces 6.1 here - when update to 6.2 start fails:
[PrimeFaces 6.1 Working Example](https://github.com/kamilkrzywanski/primefaces-test/tree/fine_with_6_1)

And here's the example that breaks with the latest version (15.0.3):
[PrimeFaces Latest Version Example](https://github.com/kamilkrzywanski/primefaces-test/tree/lastest)

I have also checked with different versions of TinyMCE, but the issue persists.

Has anyone encountered a similar problem, or does anyone have suggestions on how to resolve this?

Thanks in advance!

### Reproducer

https://github.com/kamilkrzywanski/primefaces-test/tree/lastest

(also old example https://github.com/kamilkrzywanski/primefaces-test/tree/fine_with_6_1) 

### Expected behavior

After clicking 'Open calendar,' another TinyMCE editor should appear in the popup.

### PrimeFaces edition

None

### PrimeFaces version

15.0.3

### Theme

ANY

### JSF implementation

Mojarra

### JSF version

ANY

### Java version

ANY

### Browser(s)

ANY

**Comment by tandraschko** [comment]
i fixed your title

AFAICS its a issue how you embed your TinyMCE and likely a not a PrimeFaces bug

GitHub discussions would be the better place to ask for private support

i will leave this open to @melloware

**Comment by tandraschko** [comment]
see the comment in your other issue

**Comment by kamilkrzywanski** [comment]
Do you think I'm an idiot? I removed TinyMCE, and the issue is still there. It looks like there's double loading of JS functions/vars.

**Comment by melloware** [comment]
also this has nothing to do with Variable scope.  I can see you are loading the same `const` twice in the same page.  I have no idea how this worked in 6.1 but it should NEVER have worked.

**Comment by kamilkrzywanski** [comment]
I suppose it could have been wrapped in functions in version 6.1, which is why there were no errors, and the code was correct at that time. And you're right, it's not the most correct approach, but it’s worth mentioning, for example, in the migration guide that this behavior has changed.

with 6_2
![6_2](https://github.com/user-attachments/assets/1d12be66-d3fa-4d03-9902-a94ed8174a70)

vs 6_1
![6_1](https://github.com/user-attachments/assets/15fd6047-6300-4562-9bdb-64e156dc8bb7)

**Comment by melloware** [comment]
Can you submit a PR updating the migration guide?https://github.com/primefaces/primefaces/blob/master/docs/migrationguide/6_2.md
