### ISSUE TITLE
DatePicker: JS TypeError with "ui-float-label"

### ISSUE THREAD

**Issue by roccog99** [primefaces/primefaces#14345]
### Describe the bug

I upgraded PF from 14.0.8 to 14.0.12 and then I saw this problem.
When a date is selected from a datepicker - wrapped with a div with class "ui-float-label" - an error were throw and nothing work anymore (no functions calls and nothing being update). An error it's printed on the browser console.

This is a code example to reproduce the case:

```
<div class="ui-float-label" >                    
   <p:outputLabel value="Date" for="@next" class="text-base font-bold"/>
   <p:datePicker />
</div>
```

Select a date from datepicker and then this error is printed on browser console:

<img width="1920" height="132" alt="Image" src="https://github.com/user-attachments/assets/97c79bcc-bfb2-465e-8636-a509287ec958" />

I tried multiple attributes for datepicker (value, showIcon, showOnFocus) but the problem seems to appear unconditionally from the set attributes.

### Expected behavior

No error throws, function calls and update work fine

### PrimeFaces edition

Elite

### PrimeFaces version

14.0.12

### Theme

Mirage

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

### Browser(s)

Mozilla Firefox 144.0.2 (64 bit) Fedora 43

**Comment by melloware** [comment]
Can you check if it's already fixed in 15.0.9?  Trying to determine if this is an LTS only issue

**Comment by melloware** [comment]
you can see DatePicker with floatlabel works fine in 15.0.X: https://showcase.primefaces.org/ui/misc/floatLabel.xhtml

so i would say please open a ticket with your PRO account if you need 14.X fixed.

**Comment by roccog99** [comment]
I tried with 15.0.9 and the problem still exists (function call and update does not work), the error printed in the browser console is the same as mentioned before.
To do this test I removed the Mirage theme due to incompatibility with 15.X, I don't known if this could have an impact. 

I saw that in showcase works fine so I copy and paste 
```
<span class="ui-float-label">
   <p:datePicker mask="true" pattern="dd.MM.yyyy" showIcon="true" showOnFocus="false" />
   <p:outputLabel for="@previous" value="Datepicker" />
</span>
```
in my code but still getting the error

**Comment by melloware** [comment]
@roccog99 sounds like something localized to your environment.
