### ISSUE TITLE
Width of dataTable columns not automatically adapted to content width anymore

### ISSUE THREAD

**Issue by dkreye** [primefaces/primefaces#1731]
In Primefaces version 5.3.x the width of dataTable columns has been automatically adapted to the width of its content, i.e. columns with wider content have got a larger width.
Unfortunately, in version 6.0.x all table columns get the same width. As a consequence, cell content suffers from additional line breaks or is even truncated.

See attached screenshots for an example:
- Version 5.3.x:
  ![datatable 5.3.x](https://cloud.githubusercontent.com/assets/21312484/18057572/d1f6bac0-6e10-11e6-85ca-4c47a698fc18.png)
- Version 6.0.x:
  ![datatable 6.0.x](https://cloud.githubusercontent.com/assets/21312484/18057574/d6243bea-6e10-11e6-968a-57e991fa4f04.png)

Questions:
- Is this a bug or a feature?
- If it is a feature, is there a way to activate the old 5.3.x behavior?

**Comment by kukel** [comment]
show an ['mcve'](https://www.google.com/search?q=mcve+format+code) please...

**Comment by christophenoel** [comment]
Got same problem with PF 6.0
Note I'm using dynamic columns in a (scrollable) datatable.

```
	<p:dataTable id="dataTable#{popId}"   
			scrollHeight="230"
				draggableColumns="true" liveResize="true" var="record"
				resizableColumns="true" scrollable="true"
				value="#{viewer.tableView.sortedRecords}"
				rows="#{viewer.tableView.maxRowsField}">
				<p:columns id="datableColumns#{popId}" 
					value="#{viewer.tableView.filteredFields}"
					 var="field"
					columnIndexVar="fieldIndex">
...
```

**Comment by christophenoel** [comment]
This should be fixed by:
https://github.com/primefaces/primefaces/issues/2138

**Comment by tandraschko** [comment]
should be or is fixed? Would be great if you could test it.

**Comment by christophenoel** [comment]
Sorry. 
I just checked and it does not fix it at all.
Regards.

**Comment by melloware** [comment]
I can't reproduce.  

Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.
