### ISSUE TITLE
[perf] UIData#invokeOnComponent should skip clientIds which are not childs

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#2535]
for better performance and to avoid weird exceptions
like it's implemented in MyFaces

**Comment by EugeneHryz** [comment]
Seems in Primefaces 15 this behavior is not present.
This was after `org.primefaces.component.api.UIData` was split into 2 classes in 24a79d5b87329b739c44ed56d90e6c0107747940

**Comment by tandraschko** [comment]
-> new issue plz

**Comment by tandraschko** [comment]
Also note that it might be fixed in mojarra

**Comment by melloware** [comment]
I am almost positive this has been fixed in Mojarra.

**Comment by EugeneHryz** [comment]
I checked Mojarra 4.0.5 and it is indeed fixed. But in 2.3.9 it is not fixed
Thank you for response!

**Comment by melloware** [comment]
It's fixed in 2.3.21 the last version of the 2.3 Mojarra.
