### ISSUE TITLE
OutputPanel: New View-ID is created when updating a form that contains a p:outputpanel in deffered mode.

### ISSUE THREAD

**Issue by ebehmen** [primefaces/primefaces#3815]
New javax.faces.ViewState is created after updating @form in deffered load of the outputpanel

## 1) Environment
   Primefaces Community Version 6.2
   Glassfish 3.2 & Payara 4

## 2) Expected behavior
 The behavior of updating h:form or p:outputpanel should be same.

## 3) Actual behavior
 When updating h:form the deferred request returns with a new view-id.

## 4) Steps to reproduce
  Click first time on button1 to initialize the viewscopeBean.
  The second click works fine without re-initialization of viewscopeBean but a new view-id is applied.
  On the third click, the deferred loading of the panel initializes the Postconstruct method again.

  This cannot be reproduced with button2 that updates only the p:outputpanel inside the form.

## 5) Sample XHTML

```
    <h:form id="form1" >
      <p:outputPanel id="test">
        <p:commandButton id="button1" value="update form" process="@this" update="form1" actionListener="#{viewscopeBean.action()}"/>
        <p:commandButton id="button2" value="update panel" process="@this" update="test" actionListener="#{viewscopeBean.action()}"/>
        <p:outputPanel id="filterButtons" deferred="true">        
        </p:outputPanel>
      </p:outputPanel>
    </h:form>
```

## 6) Sample bean

.. @ManagedBean
  @ViewScoped
  public class ViewscopeBean implements Serializable {

    @PostConstruct
    public void initValues() {
    }

    public void action() {
    }
  }

**Comment by tandraschko** [comment]
Please try a trunk build, we already fixed something regarding deffered outputPanel.

**Comment by ebehmen** [comment]
Tried with the latest 6.3-SNAPSHOT under Payara 4.181 (JSF 2.2) but the issue is still there.

**Comment by tandraschko** [comment]
PR welcome

**Comment by tandraschko** [comment]
ok, catched the bug.

The problem comes with jquery3.
In PF 6.1, our widgets scripts on AJAX where rendered with a ready handler ($(function() {PrimeFaces.cw(...)}), which is actually fine.
The problem with jquery3 was, that those ready handlers where not executed in the order they were rendered.
So sometimes a script for a component, which is placed later in the DOM, was executed before a script for a component, which is on the top of the DOM.
This destroyed many things actually.

We decided to don't render the ready handler on AJAX anymore.
The problem now is, that the OutputPanel script is called before the ViewState field is appended to the form by our AJAX engine.
So the deffered AJAX request is done without viewstate and new viewstate will be created.

Maybe we need a own readyhandler for AJAX requests.
Need to think about it but it's not easy task.

**Comment by tandraschko** [comment]
see: https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/util/WidgetBuilder.java#L69

**Comment by tandraschko** [comment]
Could you try what happens in 6.1?
Probably it didn't work there, too

**Comment by Rapster** [comment]
@ebehmen To workaround the issue, why don't you use a `<h:panelGroup />` for the first `<p:outputPanel />`? Should work unless you need the first `<p:outputPanel />` to be deferred too

**Comment by ebehmen** [comment]
Tried with 6.1 and 6.0, still the same issue.

@Rapster unclear what you mean. I have no problem with the p:outputPanel, but updating the form directly. The p:outputPanel is the workaround.

**Comment by tandraschko** [comment]
Yep, so it didn't work ever.
Probably the easiest way to is to render directly instead deffered if updated via AJAX.

**Comment by Rapster** [comment]
@ebehmen Basically, writing `<p:outputPanel />` is just like writing `<h:panelGroup />`. See #2674

I might have misunderstood your issue, my bad... It's just seeing 2 outputpanels one on another was a strange structure (but that's probably not related to your problem)

**Comment by Rapster** [comment]
I just realized we're facing the same issue...

**Comment by Rapster** [comment]
Could it be possible to fix this using standard JSF ajax API?

**Comment by tandraschko** [comment]
How?

**Comment by Rapster** [comment]
That's my question, BalusC had a tought about it on omnifaces, but he's not planning to fix it anytime soon I think

**Comment by tandraschko** [comment]
I think we have to introduce lifecycle events on the Client and init the Scripts after all state updates

**Comment by tandraschko** [comment]
Or somehow update the states before the components by js or force that the states are rendered before components in the partial response 
EDIT: nvm, this doesnt work

**Comment by Rapster** [comment]
@ebehmen I created this component as I was facing the same issue as yours. Let me know if that works for you (with PF 6.2):

```java
package xxx.ui.jsf.xxxfaces;

import org.omnifaces.util.Faces;
import org.primefaces.context.RequestContext;
import org.primefaces.util.AjaxRequestBuilder;
import org.primefaces.util.ComponentTraversalUtils;

import javax.faces.FacesException;
import javax.faces.component.FacesComponent;
import javax.faces.component.UIComponent;
import javax.faces.component.UIComponentBase;
import javax.faces.component.UINamingContainer;
import javax.faces.context.FacesContext;
import javax.faces.context.ResponseWriter;
import java.io.IOException;
import java.util.Collections;

@FacesComponent(LazyPanel.COMPONENT_TYPE)
public class LazyPanel extends UIComponentBase {

    public static final String COMPONENT_FAMILY = "xxx.ui.jsf.xxx.component";
    public static final String COMPONENT_TYPE = "xxx.ui.jsf.xxx.component.lazypanel";

    public enum PropertyKeys {
        disabled;
    }

    @Override
    public String getFamily() {
        return COMPONENT_FAMILY;
    }

    @Override
    public void encodeBegin(FacesContext context) throws IOException {
        String clientId = getClientId(context);
        ResponseWriter writer = context.getResponseWriter();

        writer.startElement("div", null);
        writer.writeAttribute("id", clientId, "id");
        writer.writeAttribute("class", "ui-lazypanel", null);
    }

    @Override
    public void encodeChildren(FacesContext context) throws IOException {
        String clientId = getClientId(context);
        String loaded = Faces.getRequestParameter(clientId + "_loaded");

        if (loaded != null || isDisabled()) {
            super.encodeChildren(context);
        } else {
            ResponseWriter writer = context.getResponseWriter();
            String name = resolveName(this, context);
            UIComponent form = ComponentTraversalUtils.closestForm(context, this);
            if (form == null) {
                throw new FacesException("RemoteCommand '" + name + "'must be inside a form.");
            }

            AjaxRequestBuilder builder = RequestContext.getCurrentInstance(context).getAjaxRequestBuilder();

            String request = builder.init()
                    .source(clientId)
                    .form(form.getClientId(context))
                    .process(this, getId())
                    .update(this, getId())
                    .ignoreAutoUpdate(true)
                    .params(Collections.singletonMap(clientId + "_loaded", Collections.singletonList("true")))
                    .build();

            //script
            writer.startElement("script", this);
            writer.writeAttribute("type", "text/javascript", null);

            writer.write(name + " = function() {");
            writer.write(request);
            writer.write("}");

            writer.write(";$(function() {");
            writer.write(name + "();");
            writer.write("});");

            writer.endElement("script");
        }
    }

    @Override
    public void encodeEnd(FacesContext context) throws IOException {
        ResponseWriter writer = context.getResponseWriter();
        writer.endElement("div");
    }

    public boolean isDisabled() {
        return (java.lang.Boolean) getStateHelper().eval(PropertyKeys.disabled, false);
    }

    public void setDisabled(boolean disabled) {
        getStateHelper().put(PropertyKeys.disabled, disabled);
    }

    @Override
    public boolean getRendersChildren() {
        return true;
    }

    protected String resolveName(UIComponent command, FacesContext context) {
        return "command_" + command.getClientId(context).replaceAll("-|" + UINamingContainer.getSeparatorChar(context), "_");
    }
}

```

**Comment by tandraschko** [comment]
@Rapster 
Could it also be fixed when we "disable" the deffered loading when updated via AJAX?

Otherwise the real solution is only when we introduce our own lifecycle with plugins on the client side.

**Comment by Rapster** [comment]
Ignoring deffered while ajax request makes it work. I submitted a PR so you can have a look @tandraschko
