### ISSUE TITLE
Tree : Multiple selection checkbox propagation inconsistent with filter option 

### ISSUE THREAD

**Issue by zek72** [primefaces/primefaces#3926]
## 1) Environment
- PrimeFaces version: 6.2 
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version:  Apache Tomcat/8.5.32
- Affected browsers: Firefox, Chrome

## 2) Expected behavior
With or without filtering, I expected to see the same results on selection. Filtering shouldn't change the selected nodes.

![image](https://user-images.githubusercontent.com/22317265/43638156-07c3f00a-9718-11e8-9e70-2064d82c5fcf.png)

## 3) Actual behavior
All the parent nodes are selected automatically after filtering and only selecting one single node, not all the children of that node.
![image](https://user-images.githubusercontent.com/22317265/43638257-65545138-9718-11e8-956d-0ee0fb89e7d6.png)

## 4) Steps to reproduce
Example is below.

## 5) Sample XHTML
    <h:form id="selection">
        <p:growl id="msgs" showDetail="true" escape="false"/>
        <h3>Checkbox</h3>
        <p:tree id="multiCourtTree" value="#{propagationSelectionView.root}" var="_doc"
                    selectionMode="checkbox" propagateSelectionUp="true" propagateSelectionDown="true"
                    filterBy="#{_doc.name}" filterMatchMode="contains"
                    selection="#{propagationSelectionView.selectedNodes}">
            <p:treeNode>
                <h:outputText value="#{_doc.name}"/>
            </p:treeNode>
        </p:tree>
    </h:form>

## 6) Sample bean

public class PropagationSelectionView {

    private TreeNode root;
    private TreeNode[] selectedNodes;

    @PostConstruct
    public void init() {
        root = createCheckboxDocuments();
    }

    public TreeNode createCheckboxDocuments() {
        TreeNode root = new CheckboxTreeNode(new Document("Files"), null);

        TreeNode documents = new CheckboxTreeNode(new Document("Documents"), root);
        TreeNode work = new CheckboxTreeNode(new Document("Work"), documents);
        TreeNode primefaces = new CheckboxTreeNode(new Document("PrimeFaces"), documents);

        //Documents
        TreeNode expenses = new CheckboxTreeNode(new Document("Expenses.doc"), work);
        TreeNode resume = new CheckboxTreeNode( new Document("Resume.doc"), work);
        TreeNode refdoc = new CheckboxTreeNode(new Document("RefDoc.pages"), primefaces);

        return root;
    }

    public TreeNode getRoot() {
        return root;
    }

    public TreeNode[] getSelectedNodes() {
        return selectedNodes;
    }

    public void setSelectedNodes(TreeNode[] selectedNodes) {
        this.selectedNodes = selectedNodes;
    }

    public class Document implements Serializable, Comparable<CheckboxDocument>{

        private String name;

        public Document(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        @Override
        public String toString() {
            return name;
        }

        public int compareTo(CheckboxDocument document) {
            return this.getName().compareTo(document.getName());
        }
    }
}

## 7)Conclusion

Selected Nodes should behave in the same way on whole tree structure regardless of filtering.

**Comment by eversnarf** [comment]
Same issue here. Any update?

**Comment by Rapster** [comment]
Please have a try with the last sources, it might have been by #3866

**Comment by melloware** [comment]
Attached is a test case and screenshot showing the issue is fixed.

![image](https://user-images.githubusercontent.com/4399574/63698861-ba670100-c7ed-11e9-902f-59f3284d0dc3.png)


[pf-3926.zip](https://github.com/primefaces/primefaces/files/3541596/pf-3926.zip)

**Comment by spylacopa** [comment]
I still see this error with just checked and build 7.1-SNAPSHOT,

also tried @melloware 's test case, which is also not working here

**Comment by melloware** [comment]
@spylacopa @f-r-a-n-s It might be related to this fix? https://github.com/primefaces/primefaces/issues/5089

Both issues were reported by @f-r-a-n-s

**Comment by spylacopa** [comment]
I d not think so. In your last screenshot it really looked as if it were fixed, but I cannot reproduce this.
![tree](https://user-images.githubusercontent.com/20950104/67874081-bbd9e000-fb34-11e9-81cf-9c372c161da6.png)

**Comment by melloware** [comment]
i can't reproduce the issue... I see this..
https://user-images.githubusercontent.com/4399574/63698861-ba670100-c7ed-11e9-902f-59f3284d0dc3.png

**Comment by polyluchs** [comment]
I found this issue (exactly as described in the initial post) still existing in PrimeFaces Version 8.0 and 10.0.0
Can you please check it again?

**Comment by melloware** [comment]
@polyluchs can you provide a PrimeFaces Test reproducer so we can debug the issue: https://github.com/primefaces/primefaces-test

**Comment by polyluchs** [comment]
I created a Test reproducer (see zip file below)

Without filtering the tree looks as expected when I select Banana. 
Banana is selected and Fruits is partially selected.

![expected](https://user-images.githubusercontent.com/7465418/129902777-53e7f10f-0fab-494a-a708-c372c97d653b.PNG)

I expect the same result, when I filter for "banana" and select Banana node in the filtered tree. 

I start with a clear tree, filter for "banana" and select the Banana node. 
Now the parent node Fruits becomes selected (I expect partially selected, because it has further unselected child nodes in the unfiltered tree)

![notexpected](https://user-images.githubusercontent.com/7465418/129903121-ee744115-c82c-4c9e-a1b6-2797a4d27c1c.PNG)

Then, after deleting the filter value it shows Fruits and all it's child nodes are selected (expected only Banana selected and Fruits partially selected). 

![notexpected2](https://user-images.githubusercontent.com/7465418/129904271-90361c6c-8d81-4a5c-9f66-ef4325f1b6a5.PNG)

It seems the selection is propagated up based on the filtered tree and not based on the original full tree. 


PrimeFaces Test reproducer for described example:
[3926_test.zip](https://github.com/primefaces/primefaces/files/7007358/3926_test.zip)

**Comment by melloware** [comment]
Thanks for the reproducer

**Comment by melloware** [comment]
@FlipWarthog any interest in investigating this one?

**Comment by FlipWarthog** [comment]
@melloware Yep, looking into it now.

**Comment by FlipWarthog** [comment]
@melloware I was just going to just write my analysis, but I'm also going to submit a draft PR of what I'm talking about that'll definitely need some review.

The issue itself is the result of how tree nodes are filtered out; effectively, the `TreeRenderer` is skipping them, thus they're not present in the DOM for the JS to interact with (or even know about, for that matter).

My approach to the fix is instead of keeping them out of the DOM entirely, it instead applies an additional CSS class to the `li` for the nodes being filtered out (`ui-treenode-hidden`). This fixes the reported selection issue and non-visible nodes are already handled in a lot of JS code for navigating around/interacting with.

One decision that needs to be made is what should happen if the parent is selected when one or more children are hidden. I'm not entirely sure what the answer should be so I want to try out a couple ideas. And I'll definitely need to get more integration tests in that test filter + select.

**Comment by polyluchs** [comment]
@FlipWarthog

In my web project I have extended the Checkbox Tree with a third state for the checkboxes. 
So I viewed your changes in the changesets in order to update my customized code. 
I noticed a line in JavaScript code that might lead to faulty behavior. 
I use PrimeFaces version 8.0.0 so I'm not sure if the behavior is different and correct in version 11.0.0 
Nevertheless I would like to give the hint to check the line. 

In the file tree.vertical.js in the method toggleCheckboxNode there is the modified line

`node.children('.ui-treenode-children').find('.ui-treenode:visible').find('.ui-chkbox').each(function()`

If I start with a fully collapsed tree and select a node with children, the node only gets partially selected and none of the children is selected, because initially all child nodes are not visible. When searching with filter all matching nodes get unfolded and are visible. It only works correctly for filtered tree but not for unfiltered tree.

So I suppose it was intended to select the relevant child nodes with

`node.children('.ui-treenode-children').find('.ui-treenode:not(.ui-treenode-hidden)').find('.ui-chkbox').each(function()`

and use the new style class instead of visible attribute.

**Comment by FlipWarthog** [comment]
@polyluchs ah, good catch. I think you're 100% correct on this. Let me test both ways on PF11 and see what it does, but I think this fix is accurate.

@melloware you'll have a small PR coming your way soon.

**Comment by christophs78** [comment]
We currently have following integrationtests for Tree:
![image](https://user-images.githubusercontent.com/10461942/132961376-79fc430e-bc7c-4d5a-a868-2d90029f9f04.png)
We should add integrationtests for filtering. (and filtering combined with selection)
