### ISSUE TITLE
TabView: Error when nesting a dataTable in a tabView inside another tabView

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#5580]
# IMPORTANT 

## 1) Environment
- PrimeFaces version: 8.0RC3
- Does it work on the newest released PrimeFaces version? Yes,
- Does it work on the newest sources in GitHub? No
- Application server + version: Irrelevant
- Affected browsers: All

## 2) Expected behavior

This has rendered without problems in the 8.0RC2 release candidate.

## 3) Actual behavior

The following console error appears:
TypeError: a.attr is not a function in core.js:22:3459

## 4) Steps to reproduce

Render a tabView containing a tabView containing a datatable. Sadly, I was not able to generate a reproducing sample yet.

## 5) Sample XHTML

Not yet available.

## 6) Sample bean

Not yet available.

**Comment by tandraschko** [comment]
Without reproducer -> invalid

**Comment by stolp** [comment]
It has been late yesterday - I updated the reproducer from #5581 to use the correct primefaces version and the issue is now reproducible.
[pf-5580+5581.zip](https://github.com/primefaces/primefaces/files/4147150/pf-5580%2B5581.zip)

**Comment by tandraschko** [comment]
Ok. Can you find the breaking commit please?
Or can you try to use the github master? We already fixed something related to JS attr() in RC3

**Comment by stolp** [comment]
Will try with master.

**Comment by stolp** [comment]
Apparently this works on master with the reproducer, thanks for the hint.

I will crosscheck master with my application later to make this safe.

#5581 is not related to this, the error is still there.

**Comment by stolp** [comment]
I crosschecked with master in my application. This error is resolved with master. I think this issue can be safely closed now.
