### ISSUE TITLE
BreadCrumb: should not render separators in HTML

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#6870]
It does not comply with WAI-ARIA. See https://www.w3.org/TR/wai-aria-practices/examples/breadcrumb/index.html

> To prevent screen reader announcement of the visual separators between links, they are added via CSS:
The separators are part of the visual presentation that signifies the breadcrumb trail, which is already semantically represented by the nav element with its label of Breadcrumb. So, using a display technique that is not represented in the accessibility tree used by screen readers prevents redundant and potentially distracting verbosity.

See also https://github.com/primefaces/primefaces/commit/4260e749c00648c86ba0a29ea5dc0e418206ff9a#r46150813

**Comment by jepsar** [comment]
Also, the themes still use `ul` instead of `ol`. I think, one I've fixed the HTML, we need a new issue to fix the themes / CSS.

**Comment by melloware** [comment]
@mertsincan I still see in the themes.css you using `ul` and not `ol` the new ordered list?

**Comment by mertsincan** [comment]
@melloware I added .ui-breadcrumb-items class to 'ol' tag. If we make a different change in the future, we can proceed without breaking the theme over existing classes instead of tags.

Note: For 'ul' tag, all our themes are now produced from PF designer. That's why we have to ensure backward compatibility.
