### ISSUE TITLE
Global Filter in DataTable is not working in PF10.0.0-RC1 

### ISSUE THREAD

**Issue by edudoda** [primefaces/primefaces#6968]
**Describe the defect**
 
Global filter in DataTable is not working in PF10.0.0-RC1 

**Reproducer**

 GlobalFilter is not working. Only UIColumn#filterBy is working, you can check it in the last show case as well

**Environment:**
 - PF Version: 10.0.0-RC1
 - JSF + version: JSF 2.2.19
 - Affected browsers: _e.g. Chrome, Safari
 
**To Reproduce**
1. Go to  https://www.primefaces.org/showcase/ui/data/datatable/filter.xhtml 
2. Filter for some word in GlobalFilter
3. Nothing happens

**Expected behavior**
Filter should work for any filterAble column, as it works per column.

**Example XHTML**
``` 
 <h:inputText id="globalFilter" onkeyup="PF('customersTable').filter()"  /> 
```

**Comment by buunsal** [comment]
Thanks for your report but @melloware fixed with https://github.com/primefaces/primefaces/commit/36b2fe415b1a7fb9600b368228c5f9fb5d617f69

**Comment by melloware** [comment]
Yep RC2 should be out soon @edudoda

**Comment by edudoda** [comment]
Thanks, @melloware , RC2 solves the problem with Global Filter in DataTable but for <p:treeTable /> it's not fixed yet, should I open a new issue?

**Comment by melloware** [comment]
Yep open a new issue.
