### ISSUE TITLE
Datatable: Exporter issue with NULL DisplayPriority

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#7324]
@melloware with the revision 572eaeee2c75fa901fb450c503b88d5912aa1ff6 from April 22, 17:39 the datatable exporter is not working anymore. the following NPE is thrown:

```
java.lang.NullPointerException
	at java.util.Comparator.lambda$comparingInt$7b0bb60$1(Comparator.java:490)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:348)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.primefaces.component.export.TableExporter.getExportableColumns(TableExporter.java:98)
	at org.primefaces.component.datatable.export.DataTableCSVExporter.addColumnFacets(DataTableCSVExporter.java:111)
	at org.primefaces.component.datatable.export.DataTableCSVExporter.doExport(DataTableCSVExporter.java:73)
	at org.primefaces.component.datatable.export.DataTableExporter$DataTableVisitCallBack.visit(DataTableExporter.java:250)
	at com.sun.faces.component.visit.FullVisitContext.invokeVisitCallback(FullVisitContext.java:127)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:691)
	at org.primefaces.component.datatable.export.DataTableExporter$DataTableVisitCallBack.lambda$invoke$0(DataTableExporter.java:269)
	at org.primefaces.util.ComponentUtils.invokeOnClosestIteratorParent(ComponentUtils.java:546)
	at org.primefaces.component.datatable.export.DataTableExporter$DataTableVisitCallBack.invoke(DataTableExporter.java:267)
	at org.primefaces.component.datatable.export.DataTableExporter.export(DataTableExporter.java:211)
	at org.primefaces.component.export.DataExporter.processAction(DataExporter.java:159)
```

i hope that you have an idea what has been broken here. many thanks in advance for fixing.

**Comment by melloware** [comment]
@tuerker Are you using the latest version I believe I already fixed this with this commit: https://github.com/primefaces/primefaces/pull/7259/files

**Comment by tuerker** [comment]
@melloware my snapshot was from May 12. i have now quickly tested the latest snapshot. the problem still is there.

**Comment by melloware** [comment]
OK can you provide your DataTable XHTML in full here so I can see what it doesn't like?  The line number here:
```
at org.primefaces.component.export.TableExporter.getExportableColumns(TableExporter.java:98)
```

Makese no sense since its this line..
```java
Map<String, ColumnMeta> columnMetadata = table.getColumnMeta();
```

And `table` is used 2 lines above so table can't be NULL.  That's what makes me think you aren't using the latest?

**Comment by melloware** [comment]
I think I might know the issue but its strange I can't reproduce in the showcase or my example.

**Comment by tuerker** [comment]
this is the error output for the latest snapshot.

```
java.lang.NullPointerException
	at java.util.Comparator.lambda$comparingInt$7b0bb60$1(Comparator.java:490)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:348)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.primefaces.component.export.TableExporter.getExportableColumns(TableExporter.java:114)
	at org.primefaces.component.datatable.export.DataTableCSVExporter.addColumnFacets(DataTableCSVExporter.java:111)
	at org.primefaces.component.datatable.export.DataTableCSVExporter.doExport(DataTableCSVExporter.java:73)
	at org.primefaces.component.datatable.export.DataTableExporter$ExportVisitCallback.visit(DataTableExporter.java:241)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)

```

**Comment by tuerker** [comment]
it is triggered via the "new" getExportableColumns() method.

**Comment by melloware** [comment]
OK that makes more sense.  
```java
 // sort by display priority
            List<ColumnMeta> columnMetas = columnMetadata.values().stream().
                        sorted(Comparator.comparingInt(ColumnMeta::getDisplayPriority))
                        .collect(Collectors.toList());
```

DisplayPriority is a `Integer` not an `int` so it can be NULL I guess. I have to guard against it being NULL.  Fix coming...

**Comment by tuerker** [comment]
great. thanks.

**Comment by melloware** [comment]
@tuerker its now merged do you mind pulling it down and testing with your test case? Please report back!

**Comment by tuerker** [comment]
many thanks. it now works again.

**Comment by melloware** [comment]
Excellent thanks for testing.
