### ISSUE TITLE
<h:body onload/> does not work on FF in 10.0.3  - Probably related to #7395

### ISSUE THREAD

**Issue by wlhUser** [primefaces/primefaces#7478]
With PF 10.0.3 **onload** events on **<h:body/>** are not executed in FF (89.02) any longer. - on Chrome and Edge it works fine. In 10.0.2 it worked on FF as well.

Example:
...
```
<h:body onload="console.log('Here I am')">
... content ..
</h:body>
```

On Chrome, and Edge, the 'onload'-js will be executed - on FF not.

Taking a look at the rendered HTML, you see that it is different on FF compared to the other browsers.

**EDGE, Chrome**:
```
<body onload="console.log('Here I am')">
..content ..
</body>
```

**FF**: 
```
<body>
<script>/*FIREFOX_FOUC_FIX*/</script>
<div onload="console.log('Here I am')">
</div>
.. content..
</body>
```

Suppose the support of the 'onload' method in the 'div' tag may not be standard.

**Comment by buunsal** [comment]
We confirmed the issue source is this PR: https://github.com/primefaces/primefaces/issues/7395 
We are planning to relase a version 10.0.4 this week and revert this PR changes.
Also can you check if it works correctly in 11? @wlhUser

**Comment by wlhUser** [comment]
@sqores I can check on the released PF versions. 11 is not accessible for me.

**Comment by buunsal** [comment]
OK, no problem. @melloware tested it and said he didn't see a issue. @tandraschko can you please check too?

**Comment by buunsal** [comment]
Also I didn't see a issue with 11 when I tested it. Which missing fix might be causing this issue in 10.0.3 any ideas @tandraschko @melloware ?

**Comment by tandraschko** [comment]
the issue just occurs when you have attributes on h:body
i think melloware will try to fix it, otherwise we will revert it

**Comment by buunsal** [comment]
@tandraschko  also there was another pro issue that opened last week. And the pro user said that the values sent by ajax are different in firefox and only with version 10.0.3. The issue has been fixed with the new jar we reverted the #7395. I don't know the source of the issue but I hope there is no issue with 11.

**Comment by tandraschko** [comment]
@sqores can you provide a reproducer for that AJAX values issue? Otherwise we will never know...

**Comment by buunsal** [comment]
We talked about this with @melloware and he tested it in 11 and didn't encounter a issue. Just keep that in mind if you see something not working in firefox.

I'll still create a reproducer and test it again with 11.

**Comment by buunsal** [comment]
@wlhUser 10.0.4 released please try with it. The issue should be resolved.

**Comment by tandraschko** [comment]
@sqores why did you close it? you didnt commit anything in trunk and i dont think this is fixed in trunk

**Comment by tandraschko** [comment]
its even more worse:
```
Caused by: java.lang.IllegalStateException: Must be called before the start element is closed (attribute 'onload')
    at org.apache.myfaces.shared.renderkit.html.HtmlResponseWriterImpl.writeAttribute (HtmlResponseWriterImpl.java:821)
    at org.primefaces.application.resource.MoveScriptsToBottomResponseWriter.writeAttribute (MoveScriptsToBottomResponseWriter.java:147)
    at org.primefaces.renderkit.CoreRenderer.renderPassThruAttributes (CoreRenderer.java:105)
```

**Comment by buunsal** [comment]
@tandraschko  I've been working on it since last week As far as we know it doesn't have a solution and it doesn't affect 11. @melloware also couldn't find a solution. I closed it because it's only a 10.0.3 issue. You can open it back if you want.

**Comment by tandraschko** [comment]
@melloware i fixed the renderer part
could you check if it still fixes the initial issue?

This would now produce:

```
<body onload="console.log('Here I am')">
        ... content ..
        <script>/*FIREFOX_FOUC_FIX*/</script>
        <table....
</body>
```

for this example:

```
    <h:body onload="console.log('Here I am')">
        ... content ..
        <p:panelGrid columns="1">
            test
        </p:panelGrid>
    </h:body>
```

**Comment by wlhUser** [comment]
> 
> 
> @wlhUser 10.0.4 released please try with it. The issue should be resolved.

Have tested with 10.0.4. The issue does not occur any more - works fine.
Thanks for the quick fix.

**Comment by tandraschko** [comment]
@melloware 

my new fix has some downsides:
1) if you ONLY have simple text inside the body, the FOUC isnt rendered
2) if you have simple text before any other element, the FOUC is rendered after the text, before the next element starts

i dont think 1) is realistic
im not sure if 2) fixes your initial issue

**Comment by melloware** [comment]
Yes I worked with @squores last week and even tried to use the exact same setup the PRO user had and I could not reproduce the AJAX issue with Firefox.    Let me retest after these fixes.  Honestly as long as it fixes the main issue @stolp and I see with a normal JSF project using what I would consider normal `<h:body>` template I will be happy with it.

**Comment by melloware** [comment]
@tandraschko I have tested and I am good with your fix.  Even for 2) above it fixes the issue because there is a script in the body it still prevents the flickering because the DevTools must know they need to wait for a script to run!  Not sure if you want to close this issue or not?
