### ISSUE TITLE
DataTable:  filter/sort - wrong manipulation of list elements on Mojarra without filteredValue defined (non-lazy)

### ISSUE THREAD

**Issue by DazzlingBob** [primefaces/primefaces#7999]
### 1) Environment

PrimeFaces version: primefaces 10.0.0
Application server: jetty 9.4.44 + version: mojarra-2.3

### 2) Expected behavior

Run the sample project.

Follow these steps:
1. filter on name with value BB2
2. change all BB2 row values to BB3, press Save [result=OK]
3. remove filter BB2, press Save [result=OK]
4. sort on code, press Save [result=WRONG] data rows switch with primefaces 10!

The result must be:
509, EUR, BB, BB3, A
512, EUR, BB, BB3, B
515, EUR, BB, BB3, C
516, EUR, AA, AA, D
517, EUR, AA, AA, E

### 3) Actual behavior

The result is:
509, USA, AA, AA, A
512, USA, AA, AA, B
515, EUR, BB, BB3,  C
516, EUR, BB, BB3, D
517, EUR, BB, BB3, E

### 4) Steps to reproduce

See sample project.
This behavior is only in primefaces 10, primefaces 8 is fine.

As a remark i must mention this is only one example. Different combinations of sorting and filtering data
gives different results, even in combination with multiViewState. Also the behavior changes somehow in later primefaces versions. Still managed to get it wrong in PrimeFaces-10.0.7 elite (latest version).

### 5) Sample XHTML / Sample bean

See attached projects.

Primefaces 10:
[primefaces-test-datatable.zip](https://github.com/primefaces/primefaces/files/7389069/primefaces-test-datatable.zip)

Primefaces 8 (works as expected):
[primefaces-test-datatable-8.0.zip](https://github.com/primefaces/primefaces/files/7389071/primefaces-test-datatable-8.0.zip)

run with:
mvn clean jetty:run -Pmojarra23

**Comment by tandraschko** [comment]
please try 11.0.0-RC1

**Comment by DazzlingBob** [comment]
Just tried it with 11.0.0-RC1,  unfortunately same wrong result.

**Comment by tandraschko** [comment]
@Rapster could you also check this? may be related to https://github.com/primefaces/primefaces/issues/7951

@melloware @christophs78 maybe you can also check it and provide a IT

i would really like to get rid of all those DT refactoring bugs, which made 10.0 so bad

**Comment by melloware** [comment]
@DazzlingBob I don't see what is wrong you say "sort on code, press Save [result=WRONG]" so that is Ascending and code is AA then BB.  Why do you think the sort order should be BB then AA?

See my screenshot I followed your steps exactly and the result looks right to me?

![image](https://user-images.githubusercontent.com/4399574/138305504-3a2ba75e-891c-415c-ba19-0af7667c4121.png)

**Comment by melloware** [comment]
I think its a Mojarra issue as `-Pmyfaces23` seems to be working fine?

**Comment by tandraschko** [comment]
didnt we had a mojarra issue, which were fixed by christoph or something? maybe payara uses a old version?

**Comment by melloware** [comment]
yeah i think its fixed and Mojarra hasn't released 2.3.17 yet.

**Comment by christophs78** [comment]
The Mojarra-fix i made related to DataTable went into Mojarra 2.3.15 or 2.3.16. (https://github.com/eclipse-ee4j/mojarra/pull/4882) 
So this Mojarra-bug propably still exists.

**Comment by melloware** [comment]
**Update:** yep this works fine on MyFaces 22 and 23 and failed on Mojarra 22 and 23.  Same behavior in 10.0 and 11.0.0-SNAPSHOT.

**Comment by tandraschko** [comment]
ok
i would appreciate if you could find the source and probably create a mojarra issue + PR

**Comment by christophs78** [comment]
I may implement a integration test for this. Takes maybe 2 hours or so.
But i won´t debug all this Mojarra-madness, compare it to MyFaces and ... Time and energy are running into this with an open end. This is IMO a thing for a paid developer who can sit a day or two or three in front of this issue and analyse this. And try to do a Mojarra-fix which does not break other things. And afterwards convinces Arjan and Bauke that the fix is a good thing.

**Comment by DazzlingBob** [comment]
So the primefaces 10+ refactored datatable is more in line with myfaces.
For me this is the second datatable issue with mojarra and primefaces 10, which was not a problem in primefaces 8.
Conclusion: better switch to myfaces to avoid this kind of issues.

Is this something you agree with?

**Comment by melloware** [comment]
@DazzlingBob I always prefer MyFaces to Mojarra just because it has so many less issues than this.  But I am not telling you to do that but I will tell you on two of my prodution Jboss apps we swapped our Mojarra for MyFaces because we were facing Mojarra bugs the client wanted fixed!

**Comment by tandraschko** [comment]
hard to say

in general PF should work perfectly fine on both MyFaces and Mojarra (we have around ~30 integration tests!) and this seems to be the only case currently, which doesnt work on Mojarra.
But TBH, it could even bug a bug in PrimeFaces, we just dont know without doing some hours debugging ;D
Also UIData is probably the most complex component.

IMO MyFaces is a bit more stable and more faster but both impls are currently very great, compared to some years ago

But both impls doesnt have that many active contributors, therefor i would like to see bugs fixed and new features implemented in both impls.

**Comment by christophs78** [comment]
We have a integration-test-PR.
https://github.com/primefaces/primefaces/pull/8011

**Comment by christophs78** [comment]
@DazzlingBob : On Mojarra it´s essential to define filteredValue
```xml
<p:dataTable var="reference" value="#{dataTable028.references}" filteredValue="#{dataTable028.referencesFiltered}"
..
```

Also see integration-test PR. Once filteredValue is defined it work´s correct. (Can´t explain it from my side yet.)

Now i´m going to bed after spending two hours fiddling around on this.

**Comment by DazzlingBob** [comment]
@christophs78 Appreciate your work.
Have many xhtml pages which are comparable to the issue xhtml but are more comprehensive.
Different combinations of sorting and filtering data results in wrong manipulation of lists. The problem is that is difficult to get the exact steps to take. It mostly occurs after the data is visually sorted wrong, but many times it takes one additional sort/filter to get wrong list elements. The sorting was changed in primefaces 10 from sortField to Map<String, SortMeta> that could be the cause, but am not sure.

And yes, you are right: multiViewState and filteredValue changes the behaviour:

With mojarra-2.3.15 my test results (with a more comprehensive xhtml/bean and a lot of sort/filter steps) 

```
   PrimeFaces  multiViewState filteredValue list element result
A  10.0.4      true           true          wrong
B  10.0.4      false          true          ok
C  10.0.4      true           false         wrong
D  10.0.4      false          false         ok

E  10.0.7      true           true          ok
F  10.0.7      false          true          ok
G  10.0.7      true           false         wrong
H  10.0.7      false          false         ok
```

Spend many days to try to see a pattern to mitigate the problem.
But could not find one.

**Comment by tandraschko** [comment]
Please try 11.0 Snapshot instead of 10.0.7
There are sooo many fixes in 11.0, which are not in elite

**Comment by christophs78** [comment]
Thanks for your valuable feedback!

With 10.0.0 a lot of DataTable-refactoring had been done. We had a set of integrationtests at this point in time essentially testing single DataTable-features. What we learned since 10.0.0 is testing single features is not enough. Especially for DataTable which has all kind of state. The honest truth from my perspective is we ended up with alarming broken DataTable.
Since 10.0.0 we did a lot of fixing on this end. And almost (?) always added additional integrationtests when fixing a DataTable-bug. As a community we care about the Master-branch. We do not have access to the Elite-branches. So PrimeTek took some of our post 10.0.0 community-fixes and backported them to 10.0.x-Elite.

When i look at your results we see at least 10.0.0.7 always work correct when used on Mojarra together with filteredValue. So this should be at least for now a way to work-around our still left Mojarra+DataTable-issues.

Some in-depth analysis:
https://github.com/primefaces/primefaces/blob/b3b328c53cef4ebe72d68fe495274595c453a107/primefaces/src/main/java/org/primefaces/component/datatable/DataTable.java#L932-L941
When filteredValue is defined this list get´s updated. Without filteredValue defined state is IMO stored via StateHelper. And there may be differences between Mojarra und MyFaces.

When we look at https://github.com/primefaces/primefaces/blob/9d0ec82119d20df6669d014559d0d7964d8befe1/primefaces/src/main/java/org/primefaces/component/datatable/feature/FilterFeature.java since 10.0.0 updateFilteredValue is called only once. (during filter-method)

As of 8.0 it was called first during encode and later during filter. (https://github.com/primefaces/primefaces/blob/8.0/src/main/java/org/primefaces/component/datatable/feature/FilterFeature.java)
Maybe this is makes some difference with Mojarra.

SortFeature also had some refactorings, but i don´t find major differences regarding updateFilteredValue.

@tandraschko: Without filteredValue it´s still broken on Mojarra. Our new integrationtest only works because i use filteredValue. (https://github.com/primefaces/primefaces/blob/b3b328c53cef4ebe72d68fe495274595c453a107/primefaces-integration-tests/src/main/webapp/datatable/dataTable028.xhtml#L37-L39)

**Comment by tandraschko** [comment]
@christophs78 can you try to add the second updateFilteredValue call and see if it fixes it?

**Comment by christophs78** [comment]
> @christophs78 can you try to add the second updateFilteredValue call and see if it fixes it?

I tried it last weekend but it does not fix this issue.

**Comment by tandraschko** [comment]
i think the whole thing is a design mistake by DT in general and should be:

1) after filter, items from `value` are stored in a new list `filteredValue`
2) after state restore, `value` is set to the list from `filteredValue`
3) after state save, `filteredValue` is removed from `value` (we just reset value completelly); so the next requests either gets the `value` from the bean again or the saved `filteredValue` (either from bean if the attr is defined, or from state)

the problem now occurs with editing:
when you change a value, which pojo will be changed? the one from `value` or `filteredValue`? the one from `filteredValue` of course.
if you have a expression bound to `filteredValue` and the source has the same scope like the `value` (most likely the same bean), there will be no problem as the POJO is the exact same instance.
But if you dont use the `filteredValue` expression, the new list with filtered values will be saved in the viewstate, which is, depending on `javax.faces.SERIALIZE_SERVER_STATE`, serialized each request. So you actually edit a new serialized instance POJO instead the one from your bean `value`.

So in theory the case should work on both JSF impls when `javax.faces.SERIALIZE_SERVER_STATE` is set to false. 

So there are some open questions IMO:

1) does `javax.faces.SERIALIZE_SERVER_STATE=false` fix the example for you guys?
2) why did it work on 8.0? maybe @rapster has some idea if he refactored something regarding value/filteredValue
3) Whats the best way to fix it? maybe just to remeber the filteredRowKeys and skip other items - and dont work on 2 seperate lists

**Comment by christophs78** [comment]
> 1. does `javax.faces.SERIALIZE_SERVER_STATE=false` fix the example for you guys?

Does not fix the issue. Also seems like Mojarra still defaults this param to false. (see https://github.com/eclipse-ee4j/mojarra/blob/34ea4734ad479d35cb1fe3a28756ff6447969040/impl/src/main/java/com/sun/faces/config/WebConfiguration.java#L868)
MyFaces also defaults to false. (see https://github.com/apache/myfaces/blob/99ed35db749cb6c8bae7f04b884532df98c4fe8e/impl/src/main/java/org/apache/myfaces/config/MyfacesConfig.java#L1152)

~~But you point to an important point. On MyFaces DT-value is new list-instance each request. But it still has the same object-instances within the value - list.  On Mojarra we have different object-instances for each request within the value - list.~~ (wrong)

**Comment by tandraschko** [comment]
i think i would do the following for now:
1) save filteredValues in the bean, like we do currently
2) if filteredValues isnt defined, recalculate it on each request and NOT save it in viewstate

**Comment by tandraschko** [comment]
this even avoids that pojos are getting stored in viewstate + blow up session

**Comment by tandraschko** [comment]
not fixed yet, tests incorrect or still not fixed

**Comment by christophs78** [comment]
As it looks for now this issue is fixed. I need to adapt DataTable028Test and DataTable030Test a bit, because sort-order is now correct. And I´l try to combine both test´s into one which only use different XHTMLs. (comes later this day)
