### ISSUE TITLE
DatePicker: Time is not set to start / end of day when used as range filter

### ISSUE THREAD

**Issue by ltlBeBoy** [primefaces/primefaces#8351]
**Describe the defect**
A _DatePicker_ is used as custom filter in a _DataTable_'s timestamp column. The corresponding entity attribute is from type _java.util.Date_. When choosing a date range only the entries of the matching end date with a time value of _00:00:00_ are included. All other entries of the matching end date with a later time are ignored.

**Reproducer**
See [primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/7963580/primefaces-test-master.zip)
_**HINT: Start with profile**_ `-Pmojarra23`!

**Environment:**
 - PF Version: _11.0.0_
 - PF Theme: _ALL_
 - JSF + version: _Mojarra 2.3_
 - Affected browsers: _ALL_

**To Reproduce**
1. Start reproducer
2. Filter column 'localDate' by yesterday / yesterday&today / today -> works!
3. Reset filter 'localDate'
4. Filter column 'Date' by yesterday / yesterday&today / today -> **From today only the entry with time value _00:00:00_ is inlucded!**
5. Reset filter 'Date'
6. Filter column 'localDateTime' by yesterday / yesterday&today / today -> **does not work at all -> why?**

**Expected behavior**
All entries with any time value of the selected end date should be included.

**Comment by ltlBeBoy** [comment]
And if you don't want to change the default behavior, would it be possible to modify the method `DatePickerRenderer#getConvertedValue(FacesContext, UIComponent, Object)` in a way that a special range converter (implements a tagging range converter interface) can be specified? E.g.:

```
Class<?> type = resolveDateType(context, datePicker);
Converter converter = null;
if ((type != null) && ((converter = resolveConverter(context, datePicker, type)) != null) && (converter instance of DateTimeRangeConverter)) {
  // convert range by special converter
} else {
  // like before
}
```

**Comment by melloware** [comment]
Well forget the Range filter in datatable filter wouldn't this just have the same issue with straight DatePicker and range and `java.util.date` like on the Showcase Range example: https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml ???

I think what you are saying is its making it.

```
Jan 5 00:00 to Jan 6 00:00
```

And you think it should be...

```
Jan 5 00:00 to Jan 6 23:59
```

IS that what you are saying is you think the second date should be inclusive including 2 whole days instead of 1?

**Comment by ltlBeBoy** [comment]
For consistency, yes:

- When I look at the PF11 sources for the [MatchMode](https://github.com/primefaces/primefaces/blob/11.0.0/primefaces/src/main/java/org/primefaces/model/MatchMode.java), I can see that `MatchMode.RANGE` is deprecated and `MatchMode.BETWEEN` shou be used. Then I look at the [FilterFeature](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/component/datatable/feature/FilterFeature.java), and there `MatchMode.BETWEEN` is mapped to the [BetweenFilterConstraint](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/model/filter/BetweenFilterConstraint.java). And the method to check for _between_ says: `return value.compareTo(start) >= 0 && value.compareTo(end) <= 0;` (Note the **<=** which **includes** the end value).
- When you look at the reproducer and filter the column with the _LocalDate_, then you see that the end date is **included** in the filter result. So I guess that every user would expect that filtering the _Date_ column has the same result. Especially when internally a full timestamp with time value is used and the view only shows the date part.
- The [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#operator_between) says the same for _BETWEEN_ (min <= expr AND expr **<=** max)
- [Other developers find this hint useful too](https://stackoverflow.com/a/50838253/5223047). ;-)

**Comment by ltlBeBoy** [comment]
Another option would be the possibility of specifying a custom _RangeConverter_. That converter would split the range string, convert the two dates e.g. with help of the _DateTimeConverter_ and then set the time value of the end date to [LocalTime.html#MAX](https://docs.oracle.com/javase/8/docs/api/java/time/LocalTime.html#MAX). But unfortunately the conversion part is included in the method [DatePickerRenderer#getConvertedValue](https://github.com/primefaces/primefaces/blob/11.0.0/primefaces/src/main/java/org/primefaces/component/datepicker/DatePickerRenderer.java) and [BaseCalendarRenderer#getConvertedValue](https://github.com/primefaces/primefaces/blob/11.0.0/primefaces/src/main/java/org/primefaces/component/calendar/BaseCalendarRenderer.java).

**Comment by ltlBeBoy** [comment]
Btw, do you know what I did wrong at reproducer in the _LocalDateTime_ column? Filtering does not work at all there...

**Comment by jepsar** [comment]
Ah, I think I had the same discussion with @newk5 about this. Dates should be handed differently in between filters. It was about the MongoDB lazy model if I am correct.

**Comment by melloware** [comment]
Adding @jepsar as he just reworked the filters to Comparable.

**Comment by newk5** [comment]
If I understand correctly, the OP is saying the time units in a date filter should be ignored? Doesn't the datepicker allow you to specify the time units too? ( Hour: minutes) 

To be honest I do ignore the time units in most of my own code when I filter between dates since I dont usually want to include hours/minutes. What I mean by "ignore"  is that I set the start date time units to 00:00 and end date to 23:59, but this is when Im using java.util.Date. With the mongo lazy datamodel I explicitly didn't do this since I believe the hours and minutes can be set on the datepicker so it would be wrong to assume the user wants to ignore the time units by default. If I recall, What we decided to do was to make it date inclusive to whatever values are selected on the datepicker

**Comment by jepsar** [comment]
@newk5 we aligned it with PF in the MongoDB model to be consistent

**Comment by ltlBeBoy** [comment]
To be clear:
- When the **time selection is not enabled** for the _DatePicker_, I expect the start time to be set to 00:00 and the end time to be set to 23:59.
- When our client would also want to choose the start and end time, then I would also enable the time selection. But this is currently also not possible, see [#5037](https://github.com/primefaces/primefaces/issues/5037)

**Comment by jepsar** [comment]
I think I'd like to close this as invalid. The actual issue is that the between filter should convert to local date values when the filter values are local dates. This is fixed with PR #8357 

@melloware WDYT?

**Comment by ltlBeBoy** [comment]
@jepsar I would say no. Because the problem remains when you are using a _LazyDataModel_.

**Comment by jepsar** [comment]
Then you need to fix it in your lazy data model. The date picker is doing its job and gets you a list of `LocalDate`s.

We need to have a look at the JPA model though. I'm hoping we have integration tests for that.

**Comment by ltlBeBoy** [comment]
And if one is using 100 entities with a timestamp, then there have to be 100 modified models for that?
In my opinion the view layer should prepare the input of the user. In a "freestyle fashion" like _InputText_. Or preformated like _DatePicker_. And if the default behavior does not fit my needs, then I specify a converter (which I have o code and test just once). But as I mentioned before, it is not possible to specify a custom converter because the conversion part is included in the method DatePickerRenderer#getConvertedValue and BaseCalendarRenderer#getConvertedValue. This is why in my opinion the _DatePicker_ should return a useful (and correct!) result.
Edit:
Or there should be the option to specify a custom (Range-)Converter.

**Comment by jepsar** [comment]
A converter should take care of serializing to / from string. It should not modify values.

I would suggest to use an abstract lazy model and correct the end date of a date range there, once.

**Comment by ltlBeBoy** [comment]
OK, but I would not need a custom converter if the _DatePicker_ would return the correct value. If the output data type has a time part, then that time part has to be set corresponding to the selected range!

When the range _today_ - _today_ is selected, the output has to be

- `yyyy-mm-dd - yyyy-mm-dd` for _LocalDate_ data types
- `yyyy-mm-dd 00:00:00.0000000 - yyyy-mm-dd 23:59:59.999999` for _LocalDateTime_ or _Date_ data types

Adding the logical correct time part is not modifying the value.

**Comment by ltlBeBoy** [comment]
Here is a reproducer that shows the problem. Without a _DataTable_ or filtering:

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/7972595/primefaces-test-master.zip)

Please choose _today_ - _today_ as date range and take a look at the time part.

**Comment by jepsar** [comment]
@ltlBeBoy I think you are right that we need to introduce a converter for this. That way we only need to convert once, and not every row. See also #8363

**Comment by melloware** [comment]
@jepsar @ltlBeBoy please see #14918
